My Project: C:/KPK/3day.cpp File Reference
C:/KPK/3day.cpp File Reference
#include "TXLib.h"
Functions
void Titry_Begin (int pos, int PAuse)
int main ()
Рисование фигур
void txMyTriangle (double x1, double y1, double x2, double y2, double x3, double y3, COLORREF color)
Функция, которая рисует треугольник.
void DrawTree (int posX, int posY)
Функция, рисует ёлку из 5 треугольников и комеля с координатами (100, 580, 110, 600).
void DrawPlane1 (int posX, COLORREF color)
Функция, рисует самолет вид сбоку.
void DrawPlane2 (int posX, COLORREF color)
Функция, рисует самолет вид сверху.
void DrawBIRD (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу вид сверху.
void RightturnBIRD (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу сносимую ветром вправо вид, сверху.
void LeftturnBIRD (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу сносимую ветром влево, вид сверху.
void BIRDWingsUP (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу с крыльями поднятыми вверх, вид сверху.
Функции работы с самолетом
void FlyPlane1 (int posX, int PAuse)
Функция, которая отрисовывает полет самолета вид сбоку.
void FlyPlane2 (int posX, int PAuse)
Функция, которая отрисовывает приземление самолета вид сверху.
void LandingPlane (int PAuse)
Функция, которая отрисовывает процедуру высадки после приземление самолета вид сверху.
void Titry_Samolet (int pos, int PAuse)
Функция вывода титров после сцены с самолетом.
Функции передвижения и изменения размера птицы
void BIRDUP (int posX, int posY, int PAuse)
Функция отрисовывает передвижение птицы вверх.
void BIRDLEFT (int posX, int posY, int PAuse)
Функция отрисовывает передвижение птицы влево.
void BIRDRIGHT (int posX, int posY, int XCONST, int PAuse)
Функция отрисовывает передвижение птицы вправо.
void BIRDMAX ()
Функция увеличивает размер птицы.
void BIRDMIN ()
Функция уменьшения размера птицы
void BIRDVSE ()
Функция окночания существования птицы.
Function Documentation
BIRDLEFT()
void BIRDLEFT (int posX, int posY, int PAuse)
Функция отрисовывает передвижение птицы влево.
Parameters
posX X-координата сдвига от начальной точки.
posY Y-координата сдвига от начальной точки.
PAuse Время задержки кадра в милисекундах.
See also
DrawBIRD, BIRDUP, BIRDLEFT, BIRDRIGHT, BIRDMAX, BIRDMIN, BIRDVSE
Definition at line 575 of file 3day.cpp.
     {
     while  (posX >= 100)
         {
         txSetFillColor (TX_BLACK);
         txClear      ();
         txSetColor (TX_YELLOW);
         txSelectFont("Comic Sans MS", 30);
         txTextOut   (50, 50, "В ЭТОЖЕ ВРЕМЯ ОДНА МАЛЕНЬКАЯ ГОРДАЯ ПТИЧКА");
         LeftturnBIRD (posX, posY,  1,  1, TX_YELLOW, TX_GREEN);
         txSleep      (PAuse);
         posX -= 10;
         }
     DrawBIRD    (posX, posY,  1,  1, TX_YELLOW, TX_GREEN);
     txSleep     (PAuse);
     }
References DrawBIRD(), and LeftturnBIRD().
Referenced by main().
BIRDMAX()
void BIRDMAX ()
Функция увеличивает размер птицы.
See also
DrawBIRD, BIRDUP, BIRDLEFT, BIRDRIGHT, BIRDMAX, BIRDMIN, BIRDVSE
Definition at line 594 of file 3day.cpp.
     {
     int i = 0;
     while  (i <= 10)
         {
         txSetFillColor (TX_BLACK);
         txClear     ();
         txSetColor (TX_YELLOW);
         txSelectFont("Comic Sans MS", 30);
         txTextOut   (50, 50, "В ЭТОЖЕ ВРЕМЯ ОДНА МАЛЕНЬКАЯ ГОРДАЯ ПТИЧКА");
         DrawBIRD    (400, 300,  1+i,  1+i, TX_YELLOW, TX_GREEN);
         txSleep     (50);
         i++;
         }
     }
References DrawBIRD().
Referenced by main().
BIRDMIN()
void BIRDMIN ()
Функция уменьшения размера птицы
See also
DrawBIRD, BIRDUP, BIRDLEFT, BIRDRIGHT, BIRDMAX, BIRDMIN, BIRDVSE
Definition at line 612 of file 3day.cpp.
     {
     int i = 11;
     while  (i >0)
         {
         txSetFillColor (TX_BLACK);
         txClear     ();
         txSetColor (TX_YELLOW);
         txSelectFont("Comic Sans MS", 30);
         txTextOut   (50, 50, "В ЭТОЖЕ ВРЕМЯ ОДНА МАЛЕНЬКАЯ ГОРДАЯ ПТИЧКА");
         DrawBIRD    (400, 300,  i,  i, TX_YELLOW, TX_GREEN);
         txSleep     (50);
         i--;
         }
     }
References DrawBIRD().
Referenced by main().
BIRDRIGHT()
void BIRDRIGHT (int posX, int posY, int XCONST, int PAuse)
Функция отрисовывает передвижение птицы вправо.
Parameters
posX X-координата сдвига от начальной точки.
posY Y-координата сдвига от начальной точки.
XCONST X-координата до которой двигается птица.
PAuse Время задержки кадра в милисекундах.
See also
DrawBIRD, BIRDUP, BIRDLEFT, BIRDRIGHT, BIRDMAX, BIRDMIN, BIRDVSE
Definition at line 556 of file 3day.cpp.
     {
     while  (posX < XCONST)
         {
         txSetFillColor  (TX_BLACK);
         txClear         ();
         txSetColor (TX_YELLOW);
         txSelectFont("Comic Sans MS", 30);
         txTextOut   (50, 50, "В ЭТОЖЕ ВРЕМЯ ОДНА МАЛЕНЬКАЯ ГОРДАЯ ПТИЧКА");
         RightturnBIRD   (posX, posY,  1,  1, TX_YELLOW, TX_GREEN);
         txSleep         (PAuse);
         posX += 10;
         }
     DrawBIRD    (posX, posY,  1,  1, TX_YELLOW, TX_GREEN);
     txSleep     (PAuse);
     }
References DrawBIRD(), and RightturnBIRD().
Referenced by main().
BIRDUP()
void BIRDUP (int posX, int posY, int PAuse)
Функция отрисовывает передвижение птицы вверх.
Parameters
posX X-координата сдвига от начальной точки.
posY Y-координата сдвига от начальной точки.
PAuse Время задержки кадра в милисекундах.
See also
DrawBIRD, BIRDUP, BIRDLEFT, BIRDRIGHT, BIRDMAX, BIRDMIN, BIRDVSE
Definition at line 532 of file 3day.cpp.
     {
     while  (posY >= 300)
         {
         txSetFillColor (TX_BLACK);
         txClear     ();
         txSetColor  (TX_YELLOW);
         txSelectFont("Comic Sans MS", 30);
         txTextOut   (50, 50, "В ЭТОЖЕ ВРЕМЯ ОДНА МАЛЕНЬКАЯ ГОРДАЯ ПТИЧКА");
         BIRDWingsUP (posX, posY+5,  1,  1, TX_YELLOW, TX_GREEN);
         txSleep     (PAuse);
         txSetFillColor (TX_BLACK);
         txClear     ();
         txSetColor  (TX_YELLOW);
         txSelectFont("Comic Sans MS", 30);
         txTextOut   (50, 50, "В ЭТОЖЕ ВРЕМЯ ОДНА МАЛЕНЬКАЯ ГОРДАЯ ПТИЧКА");
         DrawBIRD    (posX, posY,  1,  1, TX_YELLOW, TX_GREEN);
         txSleep     (PAuse);
         posY -= 10;
         }
     }
References BIRDWingsUP(), and DrawBIRD().
Referenced by main().
BIRDVSE()
void BIRDVSE ()
Функция окночания существования птицы.
See also
DrawBIRD, BIRDUP, BIRDLEFT, BIRDRIGHT, BIRDMAX, BIRDMIN, BIRDVSE
Definition at line 630 of file 3day.cpp.
     {
     DrawBIRD      (400, 300,  1,  1, TX_YELLOW, TX_GREEN);
     txSleep       (50);
     RightturnBIRD (400, 300,  1,  1, TX_YELLOW, TX_GREEN);
     LeftturnBIRD  (400, 300,  1,  1, TX_YELLOW, TX_GREEN);
     txSleep       (50);
     txSetColor (TX_YELLOW);
     txSelectFont("Comic Sans MS", 40);
     txTextOut   (300, 400, "PTYCA NE VZLETELO");
     }
References DrawBIRD(), LeftturnBIRD(), and RightturnBIRD().
Referenced by main().
BIRDWingsUP()
void BIRDWingsUP (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу с крыльями поднятыми вверх, вид сверху.
Parameters
X0 X-координата начальной точки (центр элипса организующего туловище птицы).
Y0 Y-координата начальной точки (центр элипса организующего туловище птицы).
zoomX коофициэнт изменения размера птицы по оси Х.
zoomY коофициэнт изменения размера птицы по оси Y.
color_body Основной цвет туловища и головы.
color_wing Основной цвет клюва, крыльев и хвоста.
See also
DrawBIRD, RightturnBIRD, BIRDWingsUP
Definition at line 483 of file 3day.cpp.
     {
     txSetFillColor (color_body);
     txEllipse       (X0 - 10*zoomX, Y0 - 30*zoomY, X0 + 10*zoomX, Y0 + 30*zoomY);
     txCircle        (X0 -  1      , Y0 - 35*zoomY,       5*zoomX               );
     txMyTriangle    (X0 -  5*zoomX, Y0 - 40*zoomY-5*zoomY/2, X0 +  5*zoomX/2, Y0 - 40*zoomY-5*zoomY/2,  X0           , Y0 - 50*zoomY-5*zoomY, color_wing);//Клюв
     txMyTriangle    (X0 - 60*zoomX, Y0 - 25*zoomY, X0 - 10*zoomX, Y0 - 25*zoomY,  X0 - 10*zoomX, Y0 + 15*zoomY, color_wing);//Левое крыло
     txMyTriangle    (X0 + 60*zoomX, Y0 - 25*zoomY, X0 + 10*zoomX, Y0 - 25*zoomY,  X0 + 10*zoomX, Y0 + 15*zoomY, color_wing);//Правое крыло
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 - 15*zoomX, Y0 + 50*zoomY,  X0 - 10*zoomX, Y0 + 60*zoomY, color_wing);//Левая секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 -  5*zoomX, Y0 + 60*zoomY,  X0 +  5*zoomX, Y0 + 60*zoomY, color_wing);//Средняя секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 + 10*zoomX, Y0 + 60*zoomY,  X0 + 15*zoomX, Y0 + 50*zoomY, color_wing);//Правая секция хвоста
     }
References txMyTriangle().
Referenced by BIRDUP().
DrawBIRD()
void DrawBIRD (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу вид сверху.
Parameters
X0 X-координата начальной точки (центр элипса организующего туловище птицы).
Y0 Y-координата начальной точки (центр элипса организующего туловище птицы).
zoomX коофициэнт изменения размера птицы по оси Х.
zoomY коофициэнт изменения размера птицы по оси Y.
color_body Основной цвет туловища и головы.
color_wing Основной цвет клюва, крыльев и хвоста.
See also
RightturnBIRD, LeftturnBIRD, BIRDWingsUP
Definition at line 438 of file 3day.cpp.
     {
     txSetFillColor (color_body);
     txEllipse       (X0 - 10*zoomX, Y0 - 30*zoomY, X0 + 10*zoomX, Y0 + 30*zoomY);
     txCircle        (X0 -  1      , Y0 - 35*zoomY,       5*zoomX               );
     txMyTriangle    (X0 -  5*zoomX, Y0 - 40*zoomY-5*zoomY/2, X0 +  5*zoomX/2, Y0 - 40*zoomY-5*zoomY/2,  X0           , Y0 - 50*zoomY-5*zoomY, color_wing);//Клюв
     txMyTriangle    (X0 - 60*zoomX, Y0 -  5*zoomY, X0 - 10*zoomX, Y0 - 25*zoomY,  X0 - 10*zoomX, Y0 + 15*zoomY, color_wing);//Левое крыло
     txMyTriangle    (X0 + 60*zoomX, Y0 -  5*zoomY, X0 + 10*zoomX, Y0 - 25*zoomY,  X0 + 10*zoomX, Y0 + 15*zoomY, color_wing);//Правое крыло
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 - 15*zoomX, Y0 + 50*zoomY,  X0 - 10*zoomX, Y0 + 60*zoomY, color_wing);//Левая секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 -  5*zoomX, Y0 + 60*zoomY,  X0 +  5*zoomX, Y0 + 60*zoomY, color_wing);//Средняя секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 + 10*zoomX, Y0 + 60*zoomY,  X0 + 15*zoomX, Y0 + 50*zoomY, color_wing);//Правая секция хвоста
     }
References txMyTriangle().
Referenced by BIRDLEFT(), BIRDMAX(), BIRDMIN(), BIRDRIGHT(), BIRDUP(), and BIRDVSE().
DrawPlane1()
void DrawPlane1 (int posX, COLORREF color)
Функция, рисует самолет вид сбоку.
Parameters
posX X-координата сдвига от начальной точки.
color Основной цвет фюзеляжа, не учитывая цвет границ фигур.
See also
FlyPlane1
Definition at line 329 of file 3day.cpp.
     {
     txSetFillColor (color);
     txEllipse (100+posX,  80, 120+posX, 130);
     txEllipse (100+posX, 100, 300+posX, 140);
     txEllipse (200+posX, 120, 250+posX, 130);
     txEllipse (295+posX,  90, 305+posX, 150);
     txCircle  (300+posX, 120,   5                 );
     txEllipse (100+posX, 110, 140+posX, 130);
     }
Referenced by FlyPlane1().
DrawPlane2()
void DrawPlane2 (int posX, COLORREF color)
Функция, рисует самолет вид сверху.
Parameters
posX X-координата сдвига от начальной точки.
color Основной цвет фюзеляжа, не учитывая цвет границ фигур.
See also
FlyPlane2, LandingPlane
Definition at line 342 of file 3day.cpp.
    {
     txSetFillColor (color);
     txEllipse (200+posX,  40, 240+posX, 200);
     txEllipse (100+posX,  80, 120+posX, 160);
     txEllipse (100+posX, 100, 300+posX, 140);
     txEllipse (295+posX,  90, 305+posX, 150);
     txCircle  (300+posX, 120,   5                 );
     txEllipse (100+posX, 110, 140+posX, 130);
     }
Referenced by FlyPlane2(), and LandingPlane().
DrawTree()
void DrawTree (int posX, int posY)
Функция, рисует ёлку из 5 треугольников и комеля с координатами (100, 580, 110, 600).
Parameters
posX X-координата сдвига от начальной точки.
posY Y-координата сдвига от начальной точки.
See also
DrawTree
Definition at line 314 of file 3day.cpp.
    {
     txSetColor     (TX_BROWN);
     txSetFillColor (TX_BROWN);
     txRectangle    (100+posX, 580+posY, 110+posX, 600+posY);
     txMyTriangle   ( 60+posX, 580+posY,  80+posX, 530+posY, 105+posX, 580+posY, TX_GREEN);
     txMyTriangle   ( 80+posX, 530+posY, 105+posX, 580+posY, 130+posX, 530+posY, TX_GREEN);
     txMyTriangle   (105+posX, 580+posY, 130+posX, 530+posY, 150+posX, 580+posY, TX_GREEN);
     txMyTriangle   ( 70+posX, 530+posY, 105+posX, 490+posY, 140+posX, 530+posY, TX_GREEN);
     txMyTriangle   ( 85+posX, 490+posY, 105+posX, 450+posY, 125+posX, 490+posY, TX_GREEN);
    }
References txMyTriangle().
Referenced by FlyPlane1().
FlyPlane1()
void FlyPlane1 (int posX, int PAuse)
Функция, которая отрисовывает полет самолета вид сбоку.
Parameters
posX X-координата сдвига от начальной точки.
PAuse Время задержки кадра в милисекундах.
See also
DrawPlane1
Definition at line 367 of file 3day.cpp.
     {
     int posY = 0;
     while   (posX < 600)
         {
         txSetFillColor (TX_BLACK);
         txClear();
         txSetColor (TX_YELLOW);
         txSelectFont("Comic Sans MS", 40);
         txTextOut   (50, 50, "V NEPOGODE LETIT SAMOLET");
         txSetColor     (TX_YELLOW,5);
         DrawPlane1(posX,TX_PINK);
         DrawTree      (0-posX, posY);
         DrawTree      (100-posX, posY+10);
         DrawTree      (200-posX, posY-10);
         DrawTree      (300-posX, posY-20);
         DrawTree      (400-posX, posY+10);
         posX += 10;
         txSleep   (PAuse);
        }
     }
References DrawPlane1(), and DrawTree().
Referenced by main().
FlyPlane2()
void FlyPlane2 (int posX, int PAuse)
Функция, которая отрисовывает приземление самолета вид сверху.
Parameters
posX X-координата сдвига от начальной точки.
PAuse Время задержки кадра в милисекундах.
See also
DrawPlane2
Definition at line 391 of file 3day.cpp.
     {
     while   (posX < 200)
         {
         txSetFillColor (TX_BLACK);
         txClear();
         txSetColor  (TX_YELLOW);
         txSelectFont("Comic Sans MS", 40);
         txTextOut   (50, 50, "PROISHODIT POSADKA SAMOLETA");
         txSetColor     (TX_YELLOW,5);
         txLine      (  0,  20, 800,  00);
         txLine      (  0, 320, 800, 300);
         DrawPlane2  (posX,TX_PINK);
         posX += 10;
         txSleep     (PAuse);
         }
     }
References DrawPlane2().
Referenced by main().
LandingPlane()
void LandingPlane (int PAuse)
Функция, которая отрисовывает процедуру высадки после приземление самолета вид сверху.
Parameters
PAuse Время задержки кадра в милисекундах.
See also
DrawPlane2, Plane2
Definition at line 411 of file 3day.cpp.
     {
     int i = 0;
     while   (i < 20)
         {
         txSetFillColor (TX_BLACK);
         txClear();
         txSetColor (TX_YELLOW);
         txSelectFont("Comic Sans MS", 40);
         txTextOut   (100, 500, "VYSADKA PASSAJIROV PROSHLA SHTATNO");
         txSetColor     (TX_YELLOW,5);
         txLine    (  0,  20, 800,  00);
         txLine    (  0, 320, 800, 300);
         DrawPlane2(200,TX_PINK);
         txCircle  (450, 160+i*10    ,   5     );
         txCircle  (460, 160+(i+1)*10,   5     );
         txCircle  (440, 160+(i+1)*10,   5     );
         txCircle  (445, 160+(i+2)*10,   5     );
         txCircle  (465, 160+(i+2)*10,   5     );
         txCircle  (455, 160+(i+2)*10,   5     );
         i++;
         txSleep   (PAuse);
         }
     }
References DrawPlane2().
Referenced by main().
LeftturnBIRD()
void LeftturnBIRD (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу сносимую ветром влево, вид сверху.
Parameters
X0 X-координата начальной точки (центр элипса организующего туловище птицы).
Y0 Y-координата начальной точки (центр элипса организующего туловище птицы).
zoomX коофициэнт изменения размера птицы по оси Х.
zoomY коофициэнт изменения размера птицы по оси Y.
color_body Основной цвет туловища и головы.
color_wing Основной цвет клюва, крыльев и хвоста.
See also
DrawBIRD, RightturnBIRD, BIRDWingsUP
Definition at line 468 of file 3day.cpp.
     {
     txSetFillColor (color_body);
     txEllipse       (X0 - 10*zoomX, Y0 - 30*zoomY, X0 + 10*zoomX, Y0 + 30*zoomY);
     txCircle        (X0 -  1      , Y0 - 35*zoomY,       5*zoomX               );
     txMyTriangle    (X0 -  5*zoomX, Y0 - 40*zoomY-5*zoomY/2, X0 +  5*zoomX/2, Y0 - 40*zoomY-5*zoomY/2,  X0 -5          , Y0 - 50*zoomY-5*zoomY, color_wing);//Клюв
     txMyTriangle    (X0 - 40*zoomX, Y0 -  5*zoomY, X0 - 10*zoomX, Y0 - 25*zoomY,  X0 - 10*zoomX, Y0 + 15*zoomY, color_wing);//Левое крыло
     txMyTriangle    (X0 + 60*zoomX, Y0 - 25*zoomY, X0 + 10*zoomX, Y0 - 25*zoomY,  X0 + 10*zoomX, Y0 + 15*zoomY, color_wing);//Правое крыло
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 - 15*zoomX, Y0 + 50*zoomY,  X0 - 10*zoomX, Y0 + 60*zoomY, color_wing);//Левая секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 -  5*zoomX, Y0 + 60*zoomY,  X0 +  5*zoomX, Y0 + 60*zoomY, color_wing);//Средняя секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 - 20*zoomX, Y0 + 50*zoomY,  X0 - 25*zoomX, Y0 + 40*zoomY, color_wing);//Правая секция хвоста
     }
References txMyTriangle().
Referenced by BIRDLEFT(), and BIRDVSE().
main()
int main ()
Definition at line 294 of file 3day.cpp.
     {
     txCreateWindow ( 800, 600);
     txBegin();
     Titry_Begin    ( 800,  80);
     FlyPlane1      (   0, 100);
     FlyPlane2      (-300, 100);
     LandingPlane   ( 100);
     Titry_Samolet  (   0, 100);
     BIRDUP         ( 400, 700,  80);
     BIRDRIGHT      ( 400, 300, 700,  80);
     BIRDLEFT       ( 700, 300,  80);
     BIRDRIGHT      ( 100, 300, 400,  80);
     BIRDMAX        ();
     BIRDMIN        ();
     BIRDVSE        ();
     }
References BIRDLEFT(), BIRDMAX(), BIRDMIN(), BIRDRIGHT(), BIRDUP(), BIRDVSE(), FlyPlane1(), FlyPlane2(), LandingPlane(), Titry_Begin(), and Titry_Samolet().
RightturnBIRD()
void RightturnBIRD (double X0, double Y0, double zoomX, double zoomY, COLORREF color_body, COLORREF color_wing)
Функция, рисует птицу сносимую ветром вправо вид, сверху.
Parameters
X0 X-координата начальной точки (центр элипса организующего туловище птицы).
Y0 Y-координата начальной точки (центр элипса организующего туловище птицы).
zoomX коофициэнт изменения размера птицы по оси Х.
zoomY коофициэнт изменения размера птицы по оси Y.
color_body Основной цвет туловища и головы.
color_wing Основной цвет клюва, крыльев и хвоста.
See also
DrawBIRD, LeftturnBIRD, BIRDWingsUP
Definition at line 453 of file 3day.cpp.
     {
     txSetFillColor (color_body);
     txEllipse       (X0 - 10*zoomX, Y0 - 30*zoomY, X0 + 10*zoomX, Y0 + 30*zoomY);
     txCircle        (X0 -  1      , Y0 - 35*zoomY,       5*zoomX               );
     txMyTriangle    (X0 -  5*zoomX, Y0 - 40*zoomY-5*zoomY/2, X0 +  5*zoomX/2, Y0 - 40*zoomY-5*zoomY/2,  X0 + 5        , Y0 - 50*zoomY-5*zoomY, color_wing);//Клюв
     txMyTriangle    (X0 - 60*zoomX, Y0 - 25*zoomY, X0 - 10*zoomX, Y0 - 25*zoomY,  X0 - 10*zoomX, Y0 + 15*zoomY, color_wing);//Левое крыло
     txMyTriangle    (X0 + 40*zoomX, Y0 -  5*zoomY, X0 + 10*zoomX, Y0 - 25*zoomY,  X0 + 10*zoomX, Y0 + 15*zoomY, color_wing);//Правое крыло
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 -  5*zoomX, Y0 + 60*zoomY,  X0 +  5*zoomX, Y0 + 60*zoomY, color_wing);//Левая секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 + 10*zoomX, Y0 + 60*zoomY,  X0 + 15*zoomX, Y0 + 50*zoomY, color_wing);//Средняя секция хвоста
     txMyTriangle    (X0           , Y0 + 30*zoomY, X0 + 20*zoomX, Y0 + 50*zoomY,  X0 + 25*zoomX, Y0 + 40*zoomY, color_wing);//Правая секция хвоста
     }
References txMyTriangle().
Referenced by BIRDRIGHT(), and BIRDVSE().
Titry_Begin()
void Titry_Begin (int pos, int PAuse)
Definition at line 498 of file 3day.cpp.
     {
     while  (pos > -200)
        {
        txSetFillColor (TX_BLACK);
        txClear     ();
        txSetColor (TX_YELLOW);
        txSelectFont("Comic Sans MS", 20);
        txTextOut   (100,    pos, "По данным ФГБУ «УГМС»: в ближайщее время ожидается переменный ветер 20-25 м/с") ;
        txTextOut   (100, pos+20, "При усилении ветра рекомендуется ограничить выход из зданий, находится в помещениях.");
        txTextOut   (100, pos+40, "Важно взять под особый контроль детей и не оставлять их без присмотра. ") ;
        pos -= 5;
        txSleep     (PAuse);
        }
     }
Referenced by main().
Titry_Samolet()
void Titry_Samolet (int pos, int PAuse)
Функция вывода титров после сцены с самолетом.
Parameters
pos координата сдвига от начальной точки.
PAuse Время задержки кадра в милисекундах.
Definition at line 516 of file 3day.cpp.
     {
     while  (pos < 300)
         {
         txSetFillColor (TX_BLACK);
         txClear     ();
         txSelectFont("Comic Sans MS", 40);
         txTextOut   (pos,    pos, "SAMOLET SMOG PRIZEMLITSYIA") ;
         txTextOut   (pos, pos+60, "SLEDITE ZA POGODNYMI YAVLENIYAMI") ;
         pos+=10;
         txSleep     (PAuse);
         }
     }
Referenced by main().
txMyTriangle()
void txMyTriangle (double x1, double y1, double x2, double y2, double x3, double y3, COLORREF color)
Функция, которая рисует треугольник.
Parameters
x1 X-координата 1-й точки.
y1 Y-координата 1-й точки.
x2 X-координата 2-й точки.
y2 Y-координата 2-й точки.
x3 X-координата 3-й точки.
y3 Y-координата 3-й точки.
color
See also
DrawTree
Definition at line 356 of file 3day.cpp.
    {
     txSetColor      (color);
     txSetFillColor  (color);
     POINT MyTriangle[3] = {{x1, y1}, {x2, y2}, {x3, y3}};
     txPolygon       (MyTriangle, 3);
    }
Referenced by BIRDWingsUP(), DrawBIRD(), DrawTree(), LeftturnBIRD(), and RightturnBIRD().